
var kzg = (() => {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir ||= __filename;
  return (
function(moduleArg = {}) {

var b=moduleArg,n,p;b.ready=new Promise((a,c)=>{n=a;p=c});var u=Object.assign({},b),w="object"==typeof window,x="function"==typeof importScripts,y="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,z="",A,B,C;
if(y){var fs=require("fs"),D=require("path");z=x?D.dirname(z)+"/":__dirname+"/";A=(a,c)=>{a=E(a)?new URL(a):D.normalize(a);return fs.readFileSync(a,c?void 0:"utf8")};C=a=>{a=A(a,!0);a.buffer||(a=new Uint8Array(a));return a};B=(a,c,d,e=!0)=>{a=E(a)?new URL(a):D.normalize(a);fs.readFile(a,e?void 0:"utf8",(f,h)=>{f?d(f):c(e?h.buffer:h)})};process.argv.slice(2)}else if(w||x)x?z=self.location.href:"undefined"!=typeof document&&document.currentScript&&(z=document.currentScript.src),_scriptDir&&(z=_scriptDir),
z.startsWith("blob:")?z="":z=z.substr(0,z.replace(/[?#].*/,"").lastIndexOf("/")+1),A=a=>{var c=new XMLHttpRequest;c.open("GET",a,!1);c.send(null);return c.responseText},x&&(C=a=>{var c=new XMLHttpRequest;c.open("GET",a,!1);c.responseType="arraybuffer";c.send(null);return new Uint8Array(c.response)}),B=(a,c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d()};e.onerror=d;e.send(null)};b.print||console.log.bind(console);
var F=b.printErr||console.error.bind(console);Object.assign(b,u);u=null;var G;b.wasmBinary&&(G=b.wasmBinary);"object"!=typeof WebAssembly&&H("no native wasm support detected");var J,K=!1,L,M;function N(){var a=J.buffer;b.HEAP8=L=new Int8Array(a);b.HEAP16=new Int16Array(a);b.HEAPU8=M=new Uint8Array(a);b.HEAPU16=new Uint16Array(a);b.HEAP32=new Int32Array(a);b.HEAPU32=new Uint32Array(a);b.HEAPF32=new Float32Array(a);b.HEAPF64=new Float64Array(a)}var O=[],P=[],Q=[];
function aa(){var a=b.preRun.shift();O.unshift(a)}var R=0,S=null,T=null;function H(a){b.onAbort?.(a);a="Aborted("+a+")";F(a);K=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");p(a);throw a;}var ba=a=>a.startsWith("data:application/octet-stream;base64,"),E=a=>a.startsWith("file://"),U;U="kzg.wasm";if(!ba(U)){var ca=U;U=b.locateFile?b.locateFile(ca,z):z+ca}
function da(a){if(a==U&&G)return new Uint8Array(G);if(C)return C(a);throw"both async and sync fetching of the wasm failed";}function ea(a){if(!G&&(w||x)){if("function"==typeof fetch&&!E(a))return fetch(a,{credentials:"same-origin"}).then(c=>{if(!c.ok)throw`failed to load wasm binary file at '${a}'`;return c.arrayBuffer()}).catch(()=>da(a));if(B)return new Promise((c,d)=>{B(a,e=>c(new Uint8Array(e)),d)})}return Promise.resolve().then(()=>da(a))}
function ha(a,c,d){return ea(a).then(e=>WebAssembly.instantiate(e,c)).then(e=>e).then(d,e=>{F(`failed to asynchronously prepare wasm: ${e}`);H(e)})}function ia(a,c){var d=U;return G||"function"!=typeof WebAssembly.instantiateStreaming||ba(d)||E(d)||y||"function"!=typeof fetch?ha(d,a,c):fetch(d,{credentials:"same-origin"}).then(e=>WebAssembly.instantiateStreaming(e,a).then(c,function(f){F(`wasm streaming compile failed: ${f}`);F("falling back to ArrayBuffer instantiation");return ha(d,a,c)}))}
var V=a=>{for(;0<a.length;)a.shift()(b)},ja="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,W=a=>{if(a){for(var c=M,d=a+NaN,e=a;c[e]&&!(e>=d);)++e;if(16<e-a&&c.buffer&&ja)a=ja.decode(c.subarray(a,e));else{for(d="";a<e;){var f=c[a++];if(f&128){var h=c[a++]&63;if(192==(f&224))d+=String.fromCharCode((f&31)<<6|h);else{var r=c[a++]&63;f=224==(f&240)?(f&15)<<12|h<<6|r:(f&7)<<18|h<<12|r<<6|c[a++]&63;65536>f?d+=String.fromCharCode(f):(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else d+=
String.fromCharCode(f)}a=d}}else a="";return a},ma=(a,c,d,e)=>{var f={string:k=>{var q=0;if(null!==k&&void 0!==k&&0!==k){for(var g=q=0;g<k.length;++g){var m=k.charCodeAt(g);127>=m?q++:2047>=m?q+=2:55296<=m&&57343>=m?(q+=4,++g):q+=3}var t=q+1;g=q=X(t);m=M;if(0<t){t=g+t-1;for(var I=0;I<k.length;++I){var l=k.charCodeAt(I);if(55296<=l&&57343>=l){var na=k.charCodeAt(++I);l=65536+((l&1023)<<10)|na&1023}if(127>=l){if(g>=t)break;m[g++]=l}else{if(2047>=l){if(g+1>=t)break;m[g++]=192|l>>6}else{if(65535>=l){if(g+
2>=t)break;m[g++]=224|l>>12}else{if(g+3>=t)break;m[g++]=240|l>>18;m[g++]=128|l>>12&63}m[g++]=128|l>>6&63}m[g++]=128|l&63}}m[g]=0}}return q},array:k=>{var q=X(k.length);L.set(k,q);return q}};a=b["_"+a];var h=[],r=0;if(e)for(var v=0;v<e.length;v++){var fa=f[d[v]];fa?(0===r&&(r=ka()),h[v]=fa(e[v])):h[v]=e[v]}d=a.apply(null,h);return d=function(k){0!==r&&la(r);return"string"===c?W(k):"boolean"===c?!!k:k}(d)},oa={c:(a,c,d,e)=>{H(`Assertion failed: ${W(a)}, at: `+[c?W(c):"unknown filename",d,e?W(e):"unknown function"])},
b:(a,c,d)=>M.copyWithin(a,c,c+d),a:a=>{var c=M.length;a>>>=0;if(2147483648<a)return!1;for(var d=1;4>=d;d*=2){var e=c*(1+.2/d);e=Math.min(e,a+100663296);var f=Math;e=Math.max(a,e);a:{f=(f.min.call(f,2147483648,e+(65536-e%65536)%65536)-J.buffer.byteLength+65535)/65536;try{J.grow(f);N();var h=1;break a}catch(r){}h=void 0}if(h)return!0}return!1}},Y=function(){function a(d){Y=d.exports;J=Y.d;N();P.unshift(Y.e);R--;b.monitorRunDependencies?.(R);0==R&&(null!==S&&(clearInterval(S),S=null),T&&(d=T,T=null,
d()));return Y}var c={a:oa};R++;b.monitorRunDependencies?.(R);if(b.instantiateWasm)try{return b.instantiateWasm(c,a)}catch(d){F(`Module.instantiateWasm callback failed with error: ${d}`),p(d)}ia(c,function(d){a(d.instance)}).catch(p);return{}}();b._load_trusted_setup_from_wasm=(a,c,d,e)=>(b._load_trusted_setup_from_wasm=Y.f)(a,c,d,e);b._free_trusted_setup_wasm=()=>(b._free_trusted_setup_wasm=Y.g)();b._blob_to_kzg_commitment_wasm=a=>(b._blob_to_kzg_commitment_wasm=Y.h)(a);
b._compute_blob_kzg_proof_wasm=(a,c)=>(b._compute_blob_kzg_proof_wasm=Y.i)(a,c);b._verify_blob_kzg_proof_wasm=(a,c,d)=>(b._verify_blob_kzg_proof_wasm=Y.j)(a,c,d);b._verify_kzg_proof_wasm=(a,c,d,e)=>(b._verify_kzg_proof_wasm=Y.k)(a,c,d,e);var ka=()=>(ka=Y.m)(),la=a=>(la=Y.n)(a),X=a=>(X=Y.o)(a);b.cwrap=(a,c,d,e)=>{var f=!d||d.every(h=>"number"===h||"boolean"===h);return"string"!==c&&f&&!e?b["_"+a]:function(){return ma(a,c,d,arguments)}};var Z;T=function pa(){Z||qa();Z||(T=pa)};
function qa(){function a(){if(!Z&&(Z=!0,b.calledRun=!0,!K)){V(P);n(b);if(b.onRuntimeInitialized)b.onRuntimeInitialized();if(b.postRun)for("function"==typeof b.postRun&&(b.postRun=[b.postRun]);b.postRun.length;){var c=b.postRun.shift();Q.unshift(c)}V(Q)}}if(!(0<R)){if(b.preRun)for("function"==typeof b.preRun&&(b.preRun=[b.preRun]);b.preRun.length;)aa();V(O);0<R||(b.setStatus?(b.setStatus("Running..."),setTimeout(function(){setTimeout(function(){b.setStatus("")},1);a()},1)):a())}}
if(b.preInit)for("function"==typeof b.preInit&&(b.preInit=[b.preInit]);0<b.preInit.length;)b.preInit.pop()();qa();


  return moduleArg.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = kzg;
else if (typeof define === 'function' && define['amd'])
  define([], () => kzg);
